// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq0bHBDWbKnkrfcKR4A-YULsqj4YIFPXA',
    appId: '1:608945082315:web:301ec3c5a21967e6aff04e',
    messagingSenderId: '608945082315',
    projectId: 'portfolio-app-37b83',
    authDomain: 'portfolio-app-37b83.firebaseapp.com',
    storageBucket: 'portfolio-app-37b83.appspot.com',
    measurementId: 'G-C3WQPVQJDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj6Dwn_YtYvdNuxZYw5S4MHyJkmbXjgt0',
    appId: '1:608945082315:android:47005ff8e4c70da8aff04e',
    messagingSenderId: '608945082315',
    projectId: 'portfolio-app-37b83',
    storageBucket: 'portfolio-app-37b83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNPDvXtPAfIvRBVh_kSyNlEu77KMTP5C0',
    appId: '1:608945082315:ios:d97a7d94d66e044daff04e',
    messagingSenderId: '608945082315',
    projectId: 'portfolio-app-37b83',
    storageBucket: 'portfolio-app-37b83.appspot.com',
    iosBundleId: 'com.example.portfolioapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNPDvXtPAfIvRBVh_kSyNlEu77KMTP5C0',
    appId: '1:608945082315:ios:d97a7d94d66e044daff04e',
    messagingSenderId: '608945082315',
    projectId: 'portfolio-app-37b83',
    storageBucket: 'portfolio-app-37b83.appspot.com',
    iosBundleId: 'com.example.portfolioapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq0bHBDWbKnkrfcKR4A-YULsqj4YIFPXA',
    appId: '1:608945082315:web:715301f82c1b98f6aff04e',
    messagingSenderId: '608945082315',
    projectId: 'portfolio-app-37b83',
    authDomain: 'portfolio-app-37b83.firebaseapp.com',
    storageBucket: 'portfolio-app-37b83.appspot.com',
    measurementId: 'G-CFBZ9DZV26',
  );
}
